[package]
name = "composenest-adapters"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
composenest-application = { path = "../application" }
composenest-domain = { path = "../domain" }
getrandom = "0.3"
rusqlite = { version = "0.40.2", features = ["backup", "bundled"] }
thiserror = "2"

[dev-dependencies]
tempfile = "3"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_UI_Shell", "Win32_System_Com"] }
