[package]
name = "composenest-adapters"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
composenest-application = { path = "../application" }
composenest-domain = { path = "../domain" }
getrandom = "0.3"
rusqlite = { version = "0.40.2", features = ["backup", "bundled"] }
serde_json = "1.0"
sha2 = "0.10"
thiserror = "2"
tokio = { version = "1.53.1", features = ["process", "io-util", "time", "sync", "rt", "macros"] }

[dev-dependencies]
tempfile = "3"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_UI_Shell", "Win32_System_Com", "Win32_Storage_FileSystem", "Win32_Foundation", "Win32_Security", "Win32_System_Threading", "Win32_System_JobObjects", "Win32_Networking_WinSock"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2"
